# Generated by Django 2.0.6 on 2018-09-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='引数')),
                ('argument_type', models.CharField(max_length=255, verbose_name='引数の型')),
                ('argument_comment', models.CharField(max_length=255, verbose_name='引数の説明')),
            ],
            options={
                'db_table': 'argument',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='メソッド')),
                ('comment', models.CharField(max_length=255, verbose_name='説明')),
                ('syntax', models.CharField(max_length=255, verbose_name='構文')),
            ],
            options={
                'db_table': 'method',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='モジュール')),
                ('module_comment', models.CharField(max_length=255, verbose_name='モジュールの説明')),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.AddField(
            model_name='argument',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memo.Method', verbose_name='引数'),
        ),
    ]
