# Generated by Django 2.0.6 on 2018-09-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='memo.Module', verbose_name='モジュール'),
            preserve_default=False,
        ),
    ]
